--- ./Makefile	2018-03-10 23:13:08.548178699 +0100
+++ ./Makefile	2018-03-02 23:20:08.000000000 +0100
@@ -15,3 +15,11 @@
 	mt7603_pci.o mt7603_soc.o mt7603_main.o mt7603_init.o mt7603_mcu.o \
 	mt7603_core.o mt7603_dma.o mt7603_mac.o mt7603_eeprom.o \
 	mt7603_beacon.o mt7603_debugfs.o
+
+SRC := $(shell pwd)
+
+all:
+	$(MAKE) -C $(KERNEL_SRC) M=$(SRC)
+
+modules_install:
+	$(MAKE) -C $(KERNEL_SRC) M=$(SRC) modules_install
