#!/bin/sh

### BEGIN INIT INFO
# Provides:          uOTA
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:
### END INIT INFO

test -x /usr/bin/OTA_APP || exit 0

case "$1" in
    start)
        echo "Starting OTA_APP..."
        start-stop-daemon --start --exec /usr/bin/OTA_APP -- > /var/log/uota.log 2>&1
        ;;
    stop)
        echo "Stopping OTA_APP..."
        start-stop-daemon --stop --exec /usr/bin/OTA_APP
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: /etc/init.d/uota {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
